aws/amazon-vpc-resource-controller-k8s

test/framework/framework.go
test/framework/manifest/container.go
test/framework/manifest/deployment.go
test/framework/manifest/eniconfig.go
test/framework/manifest/jobs.go
test/framework/manifest/pod.go
test/framework/manifest/service.go
test/framework/resource/k8s/deployment/manager.go
test/framework/resource/k8s/jobs/manager.go
test/framework/resource/k8s/pod/manager.go
test/framework/resource/k8s/service/manager.go
test/framework/verify/pod.go
test/integration/windows/run.sh
test/integration/windows/windows_suite_test.go
test/integration/windows/windows_test.go

List of test cases added
- Test Networking connectivity to Service/Internet
- Create Windows Deployment behind Service of type - LB, NodePort, ClusterIP and test connection to the pods behind the service
- Create deployment multiple times and verify networking is intact
- Create pod with same name + namespace multiple time.
- Create deployment and restart vpc-resource-controller and then scale the windows deployment again to verify older IPs are not reused.

add windows integration test

---

pkg/aws/ec2/instance.go
pkg/aws/ec2/instance_test.go

*Issue #, if available:* https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/12
*Description of changes:* Add check if ec2 API returns non empty response to avoid panic when accessing the response object.

add check to verify ec2 API doesn't return empty response

---

pkg/node/manager.go
pkg/node/manager_test.go
pkg/node/node.go
pkg/node/node_test.go

*Issue #, if available:* https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/16
*Description of changes:* The node can become permanently not ready if the `LoadDetails()` returns an error of a type other than ErrInitResources as we only clean the node from cache if we get ErrInitResources error type from `InitResource`.
Changed all the errors in  `InitResource` to be wrapped in `ErrInitResources` so the node can be cleared from cache on failure to initialize the node.

return same error type on any node init failure

---

mocks/amazon-vcp-resource-controller-k8s/pkg/k8s/mock_k8swrapper.go
pkg/aws/ec2/api/helper.go
pkg/handler/warm.go
pkg/handler/warm_test.go
pkg/k8s/wrapper.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go

*Issue #, if available:* https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/15
*Description of changes:* Broadcast Events when
**Trunk ENI Creation fails**
Add event with exit code and resolution on the node event when trunk ENI Creation fails.
Testing
```
kubectl get events
63s         Warning   TrunkENICreationFailed    node/ip-192-168-215-29.us-west-2.compute.internal    Failed to create trunk interface: Error Code: UnauthorizedOperation: Please verify the cluster IAM role has AmazonEKSVPCResourceController policy
```
**Branch ENI Annotation fails**
Add event to pod if branch ENI Annotation to the pod fails.
Testing
```
Warning  BranchENIAnnotationFailed  8s (x12 over 18s)  vpc-resource-controller  failed to annotate pod with branch ENI details: pods …
```

broadcast event on failure to annoate pod and init trunk

---

test/integration/run.sh

Add E2E Integration test script that runs integration test on existing cluster.
The script assumes that you have a Cluster that supports Pod Security Group Feature and have an instance type that supports ENI Trunking.

Add integration test script

---

test/framework/framework.go
test/integration/run.sh

- Ginko integration test suite was failing for all regions other than us-west-2. This fixes the problem by initializing session with the region passed in the flag.  
- Added additional flag OS_OVERRIDE to run the script on non Linux platform.
Testing
```
OS_OVERRIDE=darwin CLUSTER_NAME=abhipth-test REGION=ca-central-1 KUBE_CONFIG_PATH=~/.kube/config ./test/integration/run.sh
Ran 15 of 15 Specs in 265.092 seconds
SUCCESS! -- 15 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

fix running integration test script for non default regions

---

main.go
test/framework/manifest/pod.go
test/framework/manifest/service.go
test/framework/resource/k8s/pod/manager.go
test/framework/resource/k8s/service/manager.go
test/integration/webhook/validating_webhook_suite_test.go
test/integration/webhook/validating_webhook_test.go
test/integration/windows/windows_suite_test.go
test/integration/windows/windows_test.go
webhook/core/annotation_validation_webhook.go
webhook/core/annotation_validation_webhook_test.go

Switched to get the old pod from the webhook request instead of getting it from the cache.
- get old pod from request instead of using cache
- add unit test cases for annotation webhook
- add integration test suite for validating annotation webhook

Get old pod from request in annotation webhook instead of cache

---

webhook/core/annotation_validation_webhook.go
webhook/core/annotation_validation_webhook_test.go
webhook/core/pod_webhook.go
webhook/core/pod_webhook_test.go

In VPC Resource Controller Mutating Webhook, Fargate pods will be filtered and annotated with matching security group defined in SecurityGroupPolicy (CRD) based on the pod selector or service account selector. It also means that after this change, VPC Resource Controller Mutating Webhook will only mutate non-fargate pods by injecting “vpc.amazonaws.com/pod-eni” into pod spec limit/request, except those with hostNetwork:True.
In this way, validation logic for pod security group on EKS Fargate is centralized with pods on node groups, which happens in VPC Resource Controller Mutating Webhook. The pod annotation here will support Fargate Scheduler to fetch pod security group information, and pass it to podENI when calling ECS runTask API.
By …

Annotate Fargate pod with matching security groups defined in SecurityGroupPolicy (CRD)

---

.github/workflows/build.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml

Unit test is breaking because of upstream issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2311
Changing integration-test actions to use manual approval till GitHub supports protected workflow - https://github.com/actions/runner/issues/494

fix unit-test and integration-test github actions

---

Dockerfile

Switching to EKS distroless non-root image.
Tests:
Security group & windows integration test on controller on EKS control plane.

Switch to EKS distroless non-root

---

Makefile

Fix build errors- Use go get to install controller-gen for backwards compatibility.

Use go get to install binaries for backwards compatibility

---

config/controller/controller.yaml
config/controller/kustomization.yaml
config/default/kustomization.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
config/sa/kustomization.yaml
config/sa/sa.yaml
controllers/apps/deployment_controller.go
controllers/apps/deployment_controller_test.go
controllers/core/configmap_controller.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/condition/mock_condtion.go
mocks/amazon-vcp-resource-controller-k8s/pkg/k8s/mock_k8swrapper.go
pkg/condition/conditions.go
pkg/condition/conditions_test.go
pkg/config/type.go
pkg/k8s/wrapper.go
pkg/k8s/wrapper_test.go
scripts/test/test-with-eksctl.sh
test/framework/resource/k8s/configmap/wrapper.go
test/framework/resource/k8s/controller/manager.go
test/integration/windows/windows_test.go

Disable the new controller if the old Controller deployment is still active or becomes active afterwards. This will help prevent two controllers running together at the same which could lead to disruption of running Pods. 

Block Windows IPAM till Old Controller Deployment is deleted

---

pkg/aws/ec2/api/eni_cleanup.go
pkg/aws/ec2/api/eni_cleanup_test.go
pkg/config/type.go

*Description of changes:* Cleanup leaked ENIs from VPC CNI Plugin as along with ENI leaked by the controller.
Testing 
1. Created two ENIs with following set of tags
```
kubernetes.io/cluster/abhipth-ci-setup-test-12: owned
eks:eni:owner: eks-vpc-resource-controller
```
```
kubernetes.io/cluster/abhipth-ci-setup-test-12: owned
eks:eni:owner: amazon-vpc-cni
```
Both ENIs were cleaned up.
```
{"level":"info","timestamp":"2021-09-28T17:33:03.703Z","logger":"eni cleaner","msg":"deleted dangling ENI successfully","eni id":"eni-0998f776a16204dc1"}
{"level":"info","timestamp":"2021-09-28T17:33:04.117Z","logger":"eni cleaner","msg":"deleted dangling ENI successfully","eni id":"eni-0ae08c52674bc47dd"}
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Clean up leaked ENI by aws-vpc-cni

---

controllers/core/pod_controller.go

*Description of changes:* The following log line is printed on controller restarts for all Pods when the nodes are being initialized making the logs very noisy hence changing to debug level.

change log level to debug level

---

scripts/test/run-canary-test.sh
test/integration/perpodsg/job_test.go
test/integration/windows/windows_test.go

- Install the latest version of add-on because of issue https://github.com/aws/amazon-vpc-cni-k8s/issues/1340.
- Disable tests on latest version of vpc-cni add-on due to issue https://github.com/aws/amazon-vpc-cni-k8s/issues/1746
- Fix flaky windows connectivity service tests.

Install latest vpc-cni in canary script and fix windows test flakiness

---

scripts/test/run-canary-test.sh

The Canary script fails for China Region because the default GOPROXY is banned in China. Switching to https://github.com/goproxy/goproxy.cn for testing in China Region.

modify go proxy link when testing in China Regions

---

scripts/test/run-canary-test.sh
scripts/test/test-with-eksctl.sh
test/framework/utils/poll.go
test/integration/windows/stress_test.go
test/integration/windows/windows_test.go

Was seeing the following mode of failures in the Canary tests over multiple runs.
1. Rate Limiting Exceeded
```
An error occurred (Throttling) when calling the AttachRolePolicy operation (reached max retries: 2): Rate exceeded
```
**Cause:** If tests for all K8s version are triggered at same time we may have this issue.
**Resolution:**  Increase the max retries and added jitter in the script that invokes the canary script.
2. Windows Pod timeout because of docker image pull
```
Windows Integration Test
/repository/vpc-resource-controller/test/integration/windows/windows_test.go:33
configMap enable-windows-ipam tests
/repository/vpc-resource-controller/test/integration/windows/windows_test.go:87
when configmap created …
```

increase timeouts/retries for canary tests

---

main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/api/mock_ec2_wrapper.go
pkg/aws/ec2/api/eni_cleanup.go
pkg/aws/ec2/api/eni_cleanup_test.go
pkg/aws/ec2/api/helper.go
pkg/aws/ec2/api/helper_test.go
pkg/aws/ec2/api/wrapper.go

Unpaginated API call DescribeNetworkInterface could put throttling on EC2. We should use DescribeNetworkInterfacePages if not specifying interface ID as parameter.
Refactoring the API call to paginated version.
*Tests:*
1. e2e tests focus on security group for pods with the setting 4 parallelism/3 nodes as stress (Passed 
```
perpodsg % CGO_ENABLED=0 GOOS=$OS ginkgo -v -timeout 40m -- -cluster-kubeconfig=$KUBE_CONFIG_PATH -cluster-name=$CLUSTER_NAME --aws-region=$AWS_REGION --aws-vpc-id $VPC_ID --ginkgo.skip=LOCAL
```
```
Ran 18 of 22 Specs in 1553.904 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 4 Skipped
PASS
Ginkgo ran 1 suite in 25m59.650309764s
Test Suite Passed
```
2. performance/soak tests with 100 nodes and 0 - 1000 pods …

Refactoring Describe ENI API calls to paginated version

---

Makefile
scripts/test/test-with-eksctl.sh

Since upgrading to Go 1.17, we need to switch to 'go install' to install controller-gen. 
From go docs:
```Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.```
This is to resolve the following error while running integration test cases:
```
make: controller-gen: Command not found
/bin/sh: /home/github-runner/go/bin/controller-gen: No such file or directory
make: *** [generate] Error 127
```

use go install to fix integration test error

---

scripts/test/lib/cluster.sh
scripts/test/run-canary-test.sh
scripts/test/test-with-eksctl.sh

1. Add missing endpoint flag to fix beta prow job failures.
2. Fix regression test error- Use```eksctl``` to scale nodegroup. The test cluster creates unmanaged nodegroups and ```aws eks``` does not know about unmanaged nodegroups. 
```
An error occurred (ResourceNotFoundException) when calling the DescribeNodegroup operation: No node group found for name: None.
```

add endpoint flag for beta test

---

test/framework/framework.go
test/framework/resource/k8s/serviceaccount/manager.go
test/integration/webhook/validating_webhook_test.go

The original node validation webhook test case don't work against v1.23 as there is no shells available in v1.23 kube-proxy.(we switched to use minimal kube-proxy image by default)
1. refactor the node validation webhook to use credentials from aws-node SA instead of exec inside pod.
2. added more test cases

refactor node validation webhook test cases

---

pkg/aws/ec2/instance.go

#116 
We need check the pointers before dereference them for in case they were not properly populated.
*Test*
```
[AfterSuite] PASSED [110.725 seconds]
[AfterSuite] 
/home/zhuhz/go/src/amazon-vpc-resource-controller-k8s/test/integration/webhook/validating_webhook_suite_test.go:83
Begin Captured GinkgoWriter Output >>
STEP: deleting the pod 08/19/22 19:14:47.716
STEP: deleting the security group policy 08/19/22 19:14:59.726
STEP: deleting the namespace 08/19/22 19:15:01.838
STEP: waiting for all the ENIs to be deleted after being cooled down 08/19/22 19:15:07.848
STEP: deleting the security group from ec2 08/19/22 19:16:37.849
<< End Captured GinkgoWriter Output
------------------------------
Ran 11 of 11 Specs in 142.736 seconds
SUCCESS! …
```

check pointer before dereference

---

docs/troubleshooting.md

#134 
EKS recently switched authentication from service account to User for VPC resource controller. This could be a breaking change. We need call this out in our doc. A PR was also created to update [amazon-eks-user-guide](https://github.com/awsdocs/amazon-eks-user-guide/pull/612)

update troubleshooting for using PSP with User authentication

---

pkg/aws/vpc/README.md

#129 
Due to divergence, we want to add a README for limit file in master branch. The other PR for release branch has been created as well (https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/131).

add readme for latest supported instances in limit file

---

scripts/test/run-canary-test.sh

Fix region ENV in canary script. 
Fixes error `An error occurred (InvalidSignatureException) when calling the DeleteAddon operation: Credential should be scoped to a valid region, not '143REGION'` when running the canary script. 

fix region in canary script

---

controllers/core/suite_test.go
go.mod
scripts/test/run-canary-test.sh
test/README.md
test/framework/resource/k8s/configmap/wrapper.go
test/framework/resource/k8s/controller/wrapper.go
test/framework/resource/k8s/deployment/wrapper.go
test/framework/resource/k8s/node/wrapper.go
test/framework/resource/k8s/pod/wrapper.go
test/framework/resource/k8s/sgp/wrapper.go
test/framework/verify/pod.go
test/integration/perpodsg/job_test.go
test/integration/perpodsg/perpodsg_suite_test.go
test/integration/perpodsg/perpodsg_test.go
test/integration/webhook/validating_webhook_suite_test.go
test/integration/webhook/validating_webhook_test.go
test/integration/windows/stress_test.go
test/integration/windows/windows_suite_test.go
test/integration/windows/windows_test.go

N/A
In #141 , some ginkgo v2 imports were removed. This became an issue when ginkgo v2 was added back in #143 . The goal is to use ginkgo v2 (currently 2.3.1) throughout this repo, so this PR re-introduces just the ginkgo v2 support that was reverted.
I validated this PR by making sure that scripts/test/run-canary-test.sh passes.

Add ginkgo v2 back to integration tests

---

scripts/test/README.md
scripts/test/run-canary-test.sh
scripts/test/run-integration-tests.sh

N/A
This PR allows for Windows tests to be skipped in integration test suites by passing the SKIP_WINDOWS_TEST environment variable. This approach was chosen rather than checking the environment variable directly in the test so that developers did not have to modify test code to run tests locally.

Add SKIP_WINDOWS_TEST environment variable to integration test scripts

---

controllers/core/pod_controller.go
controllers/core/pod_controller_test.go
main.go

#122 
We shouldn't re-queue the pods which don't have nodes and no longer exist in the cluster. This issue could happen when the nodes are churning quickly and pods are queue due to events and the nodes are gone. Differentiating node-not-ready and node-is-gone is a must to avoid orphan pods stuck in queue.

don't add orphaned pods back into pod queue

---

pkg/k8s/pod/client_wrapper.go
pkg/worker/worker.go
pkg/worker/worker_test.go

#128 
If the pod is not found, the call returns k8s API errors NotFound. If the job doesn't find the pod, worker will forget the item. If the pod has update, cache client will fetch the event and create another job for queuing.
Test result
```
{"level":"error","timestamp":"2022-10-05T00:52:26.642Z","logger":"vpc.amazonaws.com/pod-eni-worker","msg":"won't requeue a not found errored job","job":{"Operation":"Create","UID":"","PodName":"hello-world-5d97946fc7-8sgvz","PodNamespace":"default","RequestCount":1,"NodeName":""},"job":{"Operation":"Create","UID":"","PodName":"hello-world-5d97946fc7-8sgvz","PodNamespace":"default","RequestCount":1,"NodeName":""},"error":" \"default/hello-world-5d97946fc7-8sgvz\" not …
```

avoid requeuing not found pods

---

controllers/core/node_controller.go
main.go
pkg/aws/ec2/api/wrapper.go
pkg/config/loader.go
pkg/utils/httpClient.go

#104 #124 
We should increase the workers and QPS limit on client and user calling to EC2 API to help minimize the delay/latency when large cluster/node groups churning and restarting the vpc resource controller for various reasons (such as control plane updates, control plane scaling, the controller update).
Tests have been done with clusters scale of 100 nodes, 500 nodes, and 1000 nodes. Pods using the security group for pods feature have been tested with scale from 500 up to 20k.

tuning workers count and QPS limiter

---

config/rbac/leader_election_role.yaml
main.go

Kubernetes contains a MultiLock based lock in `coordination/v1` api. 
We will take the change through multiple iterations. In the first iteration, we're moving to multi lock, that allows safe migration. In a future version, we will move multilock into lease lock and complete the migration.
Guidance: https://github.com/kubernetes/kubernetes/issues/107454

move to lease based resource lock

---

test/framework/resource/k8s/serviceaccount/manager.go

Webhook e2e is failing with EKS 1.24 due to a major change in k8s 1.24. From 1.24, service account will be no longer created with token. In our test, we use SA token to authenticate. To fix this, we can create a secret assigning to the SA aws-node and use either SA token (< 1.24) or the created secrete to authenticate client (>= 1.24).
1, if SA aws-node has no token associated, creating a secret that is assigned to aws-node service account
2, if SA has token, use its token, otherwise use the new secret
*Test*
Debug log
```
DEBUG: checking SA token &ServiceAccount{ObjectMeta:{aws-node  kube-system  c0503f33-05cc-4b12-8056-79aaaf58e87c 244 0 2022-10-27 01:20:03 +0000 UTC <nil> <nil> map[] …
```

create secret to fix the no token error in webhook e2e for eks 1.24

---

controllers/core/node_controller.go
controllers/core/pod_controller.go

We increase concurrent routines in pod reconciling. This will help minimize pods creation latency, especially during high rate pods churn and restart of the controller.

increase concurrent routines for pod controller

---

scripts/test/run-canary-test.sh

N/A
Adding changes to handle canary test script failure when addon information is not available. In this case, we will skip installing the EKS-managed addon, and tests will be run against the default self-managed addon.

skip addon installation when addon info is not available

---

config/rbac/role.yaml
controllers/core/event_controller.go
controllers/core/event_controller_test.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/k8s/mock_k8swrapper.go
pkg/config/type.go
pkg/k8s/wrapper.go

We want to change how the controller knows to enable nodes with ENI trunking. The new strategy is VPC CNI broadcasting events and the controller consumes the events and then initialize network resources.
The workflow should be like 
1. user turns on the feature of Security Group for Pods
2. VPC CNI broadcasts event asking for trunk interface
3. the controller watches events and label nodes if events are valid
4. the controller initializes resources
5. VPC CNI finishes network setup on node
Since this change focus on how node gets initialized, we tested scale node to 1000 with the feature turned on.
Test Environment settings -> EKS v1.22, VPC CNI v1.11.4 or new version with the regarding changes on top of v1.11.4
Latest released controller …

create event controller, its tests, and RBAC for sgp feature

---

controllers/core/node_controller.go
controllers/core/node_controller_test.go
controllers/core/pod_controller.go
controllers/custom/builder.go
controllers/custom/custom_controller.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/condition/mock_condition.go
pkg/condition/conditions.go
pkg/condition/conditions_test.go
pkg/k8s/wrapper.go

#117 
In the PR, we are making these changes
1. In stead of use a pointer of boolean type, we are changing to use a pointer of struct with its flag as the cache sync indicator
2. in stead of making worker routine wait for cache sync, we are let them routine a retry for reconcile and retry exponentially 

change boolean pointer to struct to sync DS status

---

controllers/core/event_controller.go
controllers/core/event_controller_test.go
pkg/config/type.go
pkg/k8s/wrapper.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go

In order to let VPC CNI better manage event broadcasting, VPC resource controller should label unsupported nodes as `not-supported`. When VPC CNI finds this label value, CNI should stop sending events from these nodes.
Tests
logs from the controller
```
{"level":"info","timestamp":"2023-01-10T20:11:38.643Z","logger":"branch eni provider","msg":"failed to update unsupported node label to non-supported","NodeName":"ip-192-168-154-254.us-west-2.compute.internal","Error":null}
{"level":"info","timestamp":"2023-01-10T20:13:08.999Z","logger":"branch eni provider","msg":"failed to update unsupported node label to non-supported","NodeName":"ip-192-168-214-180.us-west-2.compute.internal","Error":null}
```
Nodes
``` …
```

support labeling node with not-supported for CNI managing events

---

controllers/core/event_controller.go
controllers/core/event_controller_test.go
controllers/core/node_controller.go
controllers/core/node_controller_test.go
go.mod
go.sum
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/mock_node.go
pkg/config/type.go
pkg/node/node.go
pkg/node/node_test.go

make change to use const for cache config
add prometheus metrics on cache ops
N/A
For larger clusters, events emitted can be very large volume. In order to maintain the event controller performance under large load situation, we should avoid calling k8s and the controller's APIs for already processed nodes although the clients are cached. 
I am adding a [BigCache](https://github.com/allegro/bigcache) which is a TTL cache with configuration as following
- sharding: 32
- max size: 2 MB
- TTL in minutes: 30
The change has been tested with Security Group for Pods with/without custom networking enabled.
By monitoring the added prometheus metrics around the cache ops, we can tell the difference from a 500 nodes cluster scaling its nodes from 0 …

adding cache for event controller querying node instances

---

controllers/core/event_controller.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go

The controller shouldn't set the trunk label to true before nodes are initialized. 
Changes:
- in `IsInstanceSupported`, only set non-supported if the node is not supported
- in manager, set the label to true only when the node is successfully initialized
- in event controller, remove the redundant trunk event check
Tests
After injecting an error in node init, the labels stay on `false`
```
(23-01-30 1:54:09) <0> [~]  
% k get no -oyaml | grep -e trunk -e eniConfig
vpc.amazonaws.com/eniConfig: us-west-2a
vpc.amazonaws.com/eniConfig: us-west-2a
vpc.amazonaws.com/has-trunk-attached: "false"
vpc.amazonaws.com/eniConfig: us-west-2a
vpc.amazonaws.com/has-trunk-attached: "false"
vpc.amazonaws.com/eniConfig: us-west-2b …
```

only set label to true when node is successfully initialized

---

controllers/core/event_controller.go
controllers/core/event_controller_test.go
pkg/provider/branch/trunk/trunk.go

This bug was found during tests enabling custom networking. The cache entry's value is incorrectly initialized and updated. Instead of updating the feature value purely based on coming event, we need to update the value based on coming event and the already cached value for another feature flag. 
For example
If SGP value has been cached, in cache --> "instance-id": {1, 0}
when the custom networking event comes, the update should be 
- new entry value {0, 0}
- update the new entry based on CN feature {0, 1}
- update the new entry based on existing cache entry {1, 0} to {1, 1}
- save the entry {1, 1} into cache
This PR also adds a prometheus metrics for cache add, and fix a typo in previous code.
By submitting this pull request, I confirm …

fix a bug when cache for two features

---

pkg/provider/branch/provider.go

The controller shouldn't reclaim locks since the two methods from the caller already acquire locks.

remove lock from caller to avoid reclaim locks

---

Dockerfile
controllers/core/event_controller.go
controllers/core/event_controller_test.go
controllers/core/node_controller.go
controllers/core/node_controller_test.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/mock_node.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/node/node.go
pkg/node/node_test.go

initialize unmanaged node as well
update base image to latest
In the PR, I am proposing three changes
1. using more specific filters/conditions in manager resource cache for events, event controller setup with manager. This can help avoid cache/watch too many events which can cause high memory/cpu utilization in some case.
2. initializing unmanaged nodes as well to avoid dereference nil pointer when calling those nodes' fields
3. updating base image to gain latest patches
Tests have been done for 
1. Integration tests for webhook, SGP feature, and Windows
2. Scaling tests have been done with 3k to 10k pods in a cluster having 400 - 1k nodes
3. Stress tests have been done with flooding events into the cluster every second
4. API call …

Add more filters to bring down memory usage

---

.github/workflows/automated-tests.yaml

Use Pluto to scan for deprecated k8s apiGroups
https://github.com/FairwindsOps/pluto

support action to detect deprecated apiGroups

---

go.mod
go.sum
pkg/aws/ec2/instance.go
pkg/utils/math.go
pkg/utils/math_test.go

#185 
Instead of using instance max interfaces for index, we should use default network card's interfaces count, especially for multi-card instance types. Currently this controller and VPC CNI only support single network card.

check default card interfaces for index

---

main.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go

This is for clean up `not-supported` label for not supported ec2 instance type since CNI will also reset as well and not support this label.

clean up node label introduced from event solution

---

Dockerfile
Makefile

N/A
This PR allows users to customize GOLANG_IMAGE and BASE_IMAGE for docker builds through Makefile
Ran `BASE_IMAGE=public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-nonroot:2023-02-22-1677092456.2 BUILD_IMAGE=public.ecr.aws/eks-distro-build-tooling/golang:1.20-gcc-al2 AWS_ACCOUNT=<REDACTED> AWS_REGION=us-west-2 make docker-build` locally and confirmed the build was succeesfully and the GOLANG_IMAGE and BASE_IMAGE overrides are in place.

Support GOLANG_IMAGE and BASE_IMAGE variables in Makefile

---

scripts/test/run-integration-tests.sh

N/A
Current integration test runs come close to the timeout threshold, occasionally breaching it, mainly in the Windows tests. This PR increases the thresholds, as the values are still reasonable.

Increase integration test timeout thresholds

---

controllers/apps/deployment_controller.go
controllers/core/configmap_controller.go
controllers/core/node_controller.go
controllers/core/pod_controller.go
controllers/custom/builder.go
controllers/custom/custom_controller.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/manager/mock_manager.go
mocks/amazon-vcp-resource-controller-k8s/pkg/provider/mock_provider.go
mocks/amazon-vcp-resource-controller-k8s/pkg/resource/mock_resources.go
pkg/aws/ec2/api/eni_cleanup.go
pkg/healthz/healthz.go
pkg/healthz/healthz_test.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/provider/branch/provider.go
pkg/provider/ip/provider.go
pkg/provider/provider.go
pkg/resource/introspect.go
pkg/resource/manager.go
pkg/resource/manager_test.go
pkg/worker/worker.go
webhooks/core/annotation_validation_webhook.go
webhooks/core/node_update_webhook.go
webhooks/core/pod_webhook.go
webhooks/core/pod_webhook_test.go

We want to add deep health check probes into individual controllers. 
The current healthz `ping` is simple and basically just checking if the VPC RC manager goroutine (main routine) is not failing. Reported customers’ cases told us the main check may not be sufficient in some cases. What we want
- if one goroutine blocks resources, the healthz need to restart the entire controller
- the healthz probes should cover all sub controllers
- the heatlhz probe should have its own timeout instead of rely on kubelet timeout
- the health status monitored by kubelet should be aggregated (one failure should fails all)
- simple ping or complicate probing real data should depend on how critical and vulnerable the targeted controller may be.
Tests have …

add healthz deep subpathes for all controllers

---

Dockerfile
Makefile

We want to support arm64 as well.
Test
Built an arm64 image deployed in m6g graviton instance. 

support arch arg in dockerfile

---

controllers/core/configmap_controller.go
controllers/core/configmap_controller_test.go

- Added a check in config map controller to reconcile when PD flag is updated. Only update nodes when either Windows IPAM flag or PD flag is changed.
- Added a test to make sure if Windows IPAM is not enabled, then even if PD flag is set to `true` in config map, PD feature will not be enabled.

updated configmap controller to reconcile when PD flag is toggled

---

main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/condition/mock_condition.go
pkg/condition/conditions.go
pkg/config/type.go
pkg/resource/manager.go
pkg/resource/manager_test.go

Added a new condition to check for prefix delegation flag in config map `amazon-vpc-cni`, so that resource manager can pass it to resource provider, which will use the condition to initialize resource pools accordingly.

added a new condition to check for prefix delegation flag

---

pkg/provider/ip/provider.go

- Added support for toggling between two IP allocation modes. If toggling from secondary IP to PD, secondary IP provider will drain its pool. If toggling from PD to secondary IP mode, IP provider will set its pool to active state by passing in a valid default resource config. 
- Updated capacity calculation to take into account existing IPv4 prefixes.

Updated IP provider to support PD feature toggles

---

mocks/amazon-vcp-resource-controller-k8s/pkg/node/mock_node.go
pkg/aws/ec2/instance.go
pkg/aws/ec2/instance_test.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/node/node.go
pkg/node/node_test.go
pkg/provider/branch/provider.go
pkg/provider/ip/eni/eni.go
pkg/provider/ip/eni/eni_test.go
pkg/provider/ip/provider.go
pkg/utils/errors.go
pkg/utils/events.go

Since this controller runs in EKS control plane, if the instance type is not supported, the error message is not available for users. To make users' debugging easier and better visibility, we should expose some of critical failures that can be mitigated from user side. Events are common use for this purpose. This change propose sending node event when 
- new instance types are not included to support for this controller (Linux SGP feature or Windows)
- instance types are in the supported types list but doesn't support trunk interface (SGP feature)
Other changes:
- refactoring how passing client to node/instance. Since node is k8s object and also carry AWS instance, I think it is making sense to add k8s/ec2 clients into node struct instead …

enable node events when instance type is not supported

---

mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/mock_instance.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/manager/mock_manager.go
mocks/amazon-vcp-resource-controller-k8s/pkg/resource/mock_resources.go
pkg/aws/ec2/instance.go
pkg/aws/ec2/instance_test.go
pkg/node/manager/manager_test.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go
pkg/provider/ip/eni/eni.go
pkg/provider/ip/eni/eni_test.go
scripts/gen_mocks.sh

Fixes #189 
Currently, when security group is not specified in ENIConfig, the trunk ENI is associated with the default security group of the VPC. The expected behavior when using vpc-cni >= v1.8.0 is to use the primary network interface security groups with secondary network interfaces. 
Changes in this PR is to associate the trunk ENI with the primary network interface security groups when ENIConfig is missing security groups. 
*Testing:*
1. Created two eniconfigs as follows-
```
[10/05/23 1:34:11] ➜  ~ kubectl get eniconfigs.crd.k8s.amazonaws.com -o yaml
apiVersion: v1
items:
- apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: | …
```

Associate primary network interface SG with the trunk-eni when SG is not specified in ENIConfig

---

controllers/core/configmap_controller.go
controllers/core/pod_controller.go
controllers/core/pod_controller_test.go
main.go
pkg/config/loader.go
pkg/config/loader_test.go
pkg/pool/pool.go
pkg/pool/pool_test.go
pkg/provider/ip/provider.go
pkg/provider/ip/provider_test.go
pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/resource/manager.go
pkg/resource/manager_test.go

- Added logic to load PD configuration params (`warm-ip-target`, `minimum-ip-target`, `warm-prefix-target`) from vpc cni config map + unit tests
- Added prefix provider to handle job requests for prefixes + unit tests
- Minor fixes on secondary IP provider and warm pool

added prefix provider and support for PD configuration params

---

README.md

#155 
In some use case, customers may need associate more than 5 security groups per pod. We updated README to describe how it can work with current limits.

Update README on how to support more than 5 Security Groups

---

test/framework/resource/aws/ec2/manager.go
test/framework/verify/pod.go
test/integration/windows/windows_test.go

- Added test cases for when PD is enabled, basic pod deployment works
- Added test cases for when PD is enabled initially, then toggled to secondary IP mode, prefixes should be released while secondary IPs are added to warm pool
- Added test cases for when PD is enabled, `warm-prefix-target` works
- Added test cases for when PD is enabled, if the old VPC RC is deployed, pod deployment should fail

added integration tests for Windows prefix delegation

---

pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go

#231 
When branch ENI provider error out from Windows provisioning, it shouldn't emit event for warning users the instance type is not supported.
Tests were done and confirmed the behavior is fixed.
- Unsupported Linux instance type node still have the warning message when trying to enable SGP feature
- Windows node no longer has the warning event when enabling Windows support through ConfigMap

Windows events were incorrectly emitted

---

pkg/aws/ec2/api/helper.go
pkg/provider/ip/eni/eni.go
pkg/provider/ip/eni/eni_test.go

- Since Windows doesn't support multi-ENI yet, we don't want to create a new ENI when the resource request cannot be fulfilled. The check for OS can be removed once multi-ENI is supported.
- Modified unit tests for above changes.

updated to not create new secondary ENI for Windows

---

pkg/node/node.go
pkg/provider/ip/provider.go
pkg/provider/ip/provider_test.go
pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/utils/helper.go
pkg/utils/helper_test.go

- Fixed the issue of missing node capacity advertisement when node start on secondary IP mode. The cause was an incorrect condition resulting in returning the function too early and skipping capacity advertisement.
- Added license statement to prefix provider file.
- Added node event for error in `InitResources` to prefix provider to be consistent with secondary IP provider.
- Added a check for nitro status when toggling from PD to secondary IP
- Refactored common code for nitro check

fixed capactiy advertisement when node start on secondary IP mode

---

pkg/node/node.go
pkg/provider/branch/provider.go
pkg/provider/ip/provider.go
pkg/utils/events.go

The argument `reason` was incorrectly used with const instead of passed value.

fix an incorrect argument passed to SendNodeEvent

---

pkg/aws/ec2/api/wrapper.go

This prometheus metric is named incorrectly
Fixing prometheus label to match the right API call

Fix prometheus metric

---

pkg/provider/ip/provider.go
pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/utils/events.go

Don't emit node event for Linux instance when checking `IsInstanceSupported` for prefix provider

fixed incorrect node event for Linux instances emitted from prefix provider

---

test/framework/utils/poll.go
test/integration/windows/windows_test.go

- Fixed the unstable test case for `minimum-ip-target`. It passed consistently for the last 5 runs.

fixed unstable test case for minimum-ip-target

---

pkg/resource/manager.go

- Resource manager has a map of health checkers for each provider. Prefix provider was missing from the map.  

added prefix provider to health checker map

---

pkg/provider/ip/eni/eni.go

- In `eniManage.InitResources`, the method didn't lock around the shared `resourceToENIMap`.  This could cause concurrency issue when the same map is used by another goroutine. For example, the same `eniManage.InitResources` could be called by `ipv4Provider.InitResource` and `ipv4Provider.ReSyncPool`.

add missing lock when ENI manager init resources

---

pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/utils/errors.go
pkg/utils/events.go

- When the subnet doesn't have enough CIDR Blocks, Windows prefix delegation mode can fail to get a new prefix from EC2, which leads to pods stuck in creating. This node event can help customers quickly identify the reason why pods fail to run and take action to resolve the issue quickly. 

emit node event when error is InsufficientCidrBlocks in Windows PD mode

---

pkg/pool/pool.go
pkg/provider/ip/provider.go
pkg/provider/prefix/provider.go
pkg/utils/errors.go

- Some log statements have incorrect number of args. Replaced `fmt.Errorf` with package-defined `utils.ErrNotFound` to be consistent.

fixed log statements with incorrect args

---

scripts/test/run-integration-tests.sh

N/A
PR to support extra ginkgo flags that can be passed to the script to skip/focus tests. `canary` test script already includes this.

Support to pass extra ginkgo flags in integration test script

---

mocks/amazon-vcp-resource-controller-k8s/pkg/pool/mock_pool.go
pkg/handler/warm.go
pkg/pool/pool.go
pkg/pool/pool_test.go
pkg/provider/ip/provider.go
pkg/provider/ip/provider_test.go
pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/utils/errors.go

- Do not resync pool for `InsufficientCidrBlocks` error as it results in unnecessary calls of `DescribeInstances`.
- Change retry wait time for`InsufficientCidrBlocks` error to 2 min.
- Add a new field in pool to indicate whether prefix is available in the subnet, so that it can inform pod controller of the error and its corresponding wait time.
- Send pod event when `InsufficientCidrBlocks` happens and pod needs to retry after 2 min.

do not resync or reconcile pool for InsufficientCidrBlocks error and add longer wait time for retry

---

scripts/test/run-integration-tests.sh

N/A
Script fails if `EXTRA_GINKGO_FLAGS` parameters is not defined. We are using `set -u` in this file which treats this as an error. With this change, we define the variable as empty if it is not defined/passed to the script

Define environment variable and set it to empty by default

---

scripts/test/run-canary-test.sh
scripts/test/run-integration-tests.sh

N/A
Adjust ginkgo timeouts in canary and full integration test script. I checked the run times over 3-5 successful jobs which also runs the full Windows PD tests. 
This is required as we are adjusting our prow job schedule and need to ensure VPC-RC tests can finish within reasonable time.
We'll be monitoring the jobs and we can adjust the timeouts if any issues. 
Also includes changes to clean up the canary script, EKS 1.17 has been out of support for a long time and we do not run EKS 1.17 tests anymore.

Adjust ginkgo timeout in test scripts

---

mocks/amazon-vcp-resource-controller-k8s/pkg/provider/mock_provider.go
pkg/pool/pool.go
pkg/provider/branch/provider.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/ip/provider.go
pkg/provider/prefix/provider.go
pkg/provider/provider.go
pkg/resource/introspect.go
pkg/resource/introspect_test.go

We should provide a summary of resource to scrape instead of full deployed pods, especially in a large clusters. 
Tests:
```
$ curl localhost:22775/resources/all
{
"vpc.amazonaws.com/PrivateIPv4Address": {},
"vpc.amazonaws.com/PrivateIPv4AddressFromPrefix": {},
"vpc.amazonaws.com/pod-eni": {
"ip-192-168-xx-x.us-west-2.compute.internal": {
"TrunkENIID": "eni-08bfxxxxxxxxxx",
"InstanceID": "i-0428xxxxxxxxxx",
"PodToBranchENI": {
"ce4bfcdf-1137-4662-b279-79d937838ac6": [
{
"eniId": "eni-0314xxxxxxxxxx",
"ifAddress": "02:8e:xx:xx:xx:xx",
"privateIp": "192.168.xx.xxx",
"vlanId": 2,
"subnetCidr": "192.168.32.0/19"
}
],
"ff42c15a-23c9-4e86-9823-731916db0d3d": [
{
"eniId": "eni-01bbxxxxxxxxxx",
"ifAddress": "02:f6:xx:xx:xx:xx",
"privateIp": …
```

Add introspecting summary to minimize the output for pods

---

controllers/core/node_controller.go
pkg/k8s/wrapper.go

Currently the node_controller is not correctly wired up with CNINode Updates. It only triggers on node events. We're currently saved by the 5 minute node heartbeat, which happens to trigger attachment trunk attachment when it happens. This can cause trunk attachment tot take between 0-5 minutes instead of near-immediate reconciliation.
Controller-runtime expects controller=true on ownerreferences for `.Owns` to correctly enqueue the node keys. 

fix: Add controller=true to ownerreferences to correctly reconcile on .Owns()

---

DEVELOPER_GUIDE.md
Makefile

This PR adds `apply-dependencies` to Makefile to install the cert manager and certificate. Also updates the developer's guide for this change. Tested in dev setup.

add make apply-dependencies and update developer guide

---

main.go
pkg/aws/ec2/api/wrapper.go
pkg/utils/helper.go
pkg/utils/helper_test.go

We want to add two extra context keys to header.
Tests have been done with extra condition in role and negative tests with incorrect key for account.

Inject extra keys to STS client request header

---

main.go

Due to the deployment gaps between systems, we may face the placeholder instead of real region in manifest. In that case, we want to use empty string to create default client.

handle the placeholder

---

main.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/utils/events.go

#216 
If the node is manageable (SGP or Windows), the controller will send one time event to the node with its version. Although we have mapping between EKS platform version and the controller version in every release note, this event can be a convenient way for customers to check from any client, such as `kubectl describe node`, in some use cases, such as automated workflows.
```
Events:
Type    Reason                   Age   From                     Message
----    ------                   ----  ----                     -------
Normal  ControllerVersionNotice  22s   vpc-resource-controller  The node is managed by VPC resource controller version v1.3.0
Normal  NodeTrunkInitiated       21s   vpc-resource-controller  The node has trunk …
```

support version notice to nodes

---

test/integration/webhook/validating_webhook_suite_test.go

N/A
This adds the update permission on aws-node for backward compatibility tests

Patch aws node role for node update permissions

---

go.mod
go.sum

N/A
Updates vpc-cni dependency to v1.13.4 

Bump down amazon-vpc-cni-k8s dependency to v1.13.4

---

controllers/core/node_controller.go
controllers/core/pod_controller.go

#295 
We are seeing pod queue latency in some extreme use case. Increasing the workers to help on performance.

increasing node and pod worker number

---

pkg/config/loader.go

Related to #295 
We have seen poor performance through metrics in large clusters when creating pods using security group for pods. Bump up the number of pod ENI workers to improve performance. 

increase pod ENI workers count

---

mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/mock_instance.go
pkg/aws/ec2/instance.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go
scripts/gen_mocks.sh

N/A
In order to support Security Groups for Pods in IPv6 clusters, the VPC Resource Controller must create trunk and branch ENIs with IPv6 addresses assigned. This happens already based on the subnet used in an IPv6 cluster, so VPC Resource Controller's next role is to annotate pods with branch ENI information.
This PR annotates pods with the IPv6 address and CIDR that is configured for the branch ENI, if there is one. The reason that IPv6 fields are added in-addition, instead of in-place is two-fold:
1. VPC Resource Controller must support older VPC CNI versions, so it cannot change existing JSON names.
2. If dual-stack is eventually supported, the pod will need IPv4 and IPv6 fields, so this change facilitates that.
I tested this code …

Annotate pods with IPv6 details from branch ENI when available

---

controllers/core/node_controller.go
controllers/core/node_controller_test.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/manager/mock_manager.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/mock_node.go
mocks/amazon-vcp-resource-controller-k8s/pkg/provider/branch/trunk/mock_trunk.go
mocks/amazon-vcp-resource-controller-k8s/pkg/provider/mock_provider.go
pkg/aws/errors/ec2_errors.go
pkg/node/manager/manager.go
pkg/node/node.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go
pkg/provider/ip/provider.go
pkg/provider/prefix/provider.go
pkg/provider/provider.go

Isolating the node based reconciliation/cleaning from worker queue to an independent one-off goroutine.

isolate node cleanup from worker queue

---

Makefile
pkg/aws/ec2/api/eni_cleanup.go
pkg/aws/ec2/api/wrapper.go

N/A
Adding new metrics for number of leaked ENIs created by VPC-RC and VPC-CNI, and cleaned up by the controller.
Also updated the golang build image in Makefile for local builds. 
*Testing:*
Manually created an ENI with tags:
```
kubernetes.io/cluster/vpcrc-release: owned
eks:eni:owner: eks-vpc-resource-controller
```
Restarted controller, waiting for 30 mins and verified the ENI is deleted. 
Metrics output: 
```
vpc_cni_created_leaked_eni_cleanup_count 0
vpc_rc_created_leaked_eni_cleanup_count 1
```

Add metrics for leaked ENI cleanup routine

---

pkg/aws/ec2/api/eni_cleanup.go
pkg/aws/ec2/api/wrapper.go

Adding metrics for leaked ENI cleanup routine- cherry pick from master branch, #328 

Add metrics for leaked ENI cleanup routine (#328)

---

.github/workflows/presubmit.yaml

We should enable go vulnerability check in actions.

adding govulnscheck to action

---

docs/sgp/workflow.md
docs/troubleshooting.md

*Issue #, if available:* N/A
Find some typos while viewing the docs. This PR is just for cleaning up these typos.

fix typo in document

---

.github/workflows/presubmit.yaml
Dockerfile
Makefile
go.mod
go.sum

We should force vulns check using latest go version.

Update VPC CNI version and force vulns check using latest go version

---

docs/troubleshooting.md

Update troubleshooting doc for CNINode change

update debugging doc

---

Makefile
pkg/worker/worker_test.go

We use maps, channels, and locks. We should test with data race detection.

add data race detection in test

---

README.md
docs/sgp/sgp_config_options.md
docs/sgp/workflow.md
docs/troubleshooting.md

N/A
Add `amazon-vpc-cni` configuration options for managing security groups for pods and update README. 
Also updated the SGPP workflow to include `CNINode` updates. 

Update docs to add amazon-vpc-cni configmap options for SGPP

---

pkg/config/loader.go
pkg/config/type.go
pkg/provider/prefix/provider_test.go
test/integration/windows/windows_test.go

#370 
Current Windows' flags name can cause confusion for Linux users. We need rename them with prefix `windows` without breaking current users' setting.

rename windows flags

---

mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/api/mock_ec2_apihelper.go
mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/api/mock_ec2_wrapper.go
pkg/aws/ec2/api/helper.go
pkg/aws/ec2/api/wrapper.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go

N/A
Call `DisassociateTrunkInterface` to remove association between branch and trunk ENI before deleting the branch ENI as per recommendation by EC2 team. 
Tests done after adding `DisassociateTrunkInterface` permission in the control plane instance role: 
* Scale up and down pods using security group for pods and verify branch ENIs can be disassociated and deleted
* Terminate nodes and verify branch ENIs are deleted- Sometimes the association is removed when trunk ENI is deleted with EC2 instance termination, in which case branch ENI is still deleted
* Upgrade from old vpc-resource-controller which is missing association ID and verify branch ENIs can be deleted for backwards compatibility. 
SGPP tests:
```
Ran 19 of 23 Specs in 929.417 …
```

Call DisassociateTrunkInterface before deleting branch ENI

---

main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/api/mock_ec2_apihelper.go
mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/api/mock_ec2_wrapper.go
pkg/aws/ec2/api/eni_cleanup.go
pkg/aws/ec2/api/eni_cleanup_test.go
pkg/aws/ec2/api/helper.go
pkg/aws/ec2/api/helper_test.go
pkg/aws/ec2/api/wrapper.go
pkg/config/type.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go

Fixes #188 
Paginate DescribeNetworkInterfaces API call by specifying a deep filter like vpc-id and subnet-id as unpaginated API call causes the operation to fail when there is a large number of network interfaces. 
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-network-interfaces.html
Unpaginated calls were used in the periodic leaked ENI cleanup routine and during trunk initialization to fetch all branch ENIs on the node. These are now paginated to use vpc-id and subnet-id respectively, and also added jitter to avoid EC2 API throttling and increased call volume to address earlier issue with pagination.
Testing:
Security group for pods test succeeded:
```
Ran 19 of 23 Specs in 975.331 seconds
SUCCESS! -- 19 Passed | 0 …
```

fix: paginate DescribeNetworkInterfaces with deep filters

---

controllers/crds/cninode_controller.go
pkg/config/type.go
pkg/k8s/wrapper.go

NA
Update the cluster tag key to be deterministic in the CNINode CRD for use in other components like VPC-CNI where cluster name might be unknown.

fix:update cluster tag name in CNINode

---

hack/toolchain.sh

We have to pin the envtest version before [the upstream issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2720#issuecomment-2016461180) is fixed.

pin envtest version due to an upstream bug

---

controllers/crds/cninode_controller.go
go.mod
go.sum
hack/toolchain.sh
pkg/k8s/finalizer.go
pkg/k8s/wrapper.go
pkg/k8s/wrapper_test.go
pkg/provider/branch/provider.go

N/A
1. Adding node OS label to CNINodes to run the finalizer routine for Linux nodes only. 
2. Added retry to get CNINode during node reconcile: When CNINode is deleted, node update is triggered and since CNINode is not immediately found, the controller updates the node to be unmanaged and adds node to delete queue and removes the trunk, this is a regression bug. CNINode is shortly re-created by the CNINode controller, so added retry with backoff to GetCNINode which prevents node being unmanaged. 
Tests:
1. CNINode creation: Validated new CNINodes are created with required fields
3. Node deletion: Validated finalizer routine is only run for Linux nodes
4. Reconcile tests: Edit CNINode to remove required fields and validated it is updated …

add node os label in CNINode and run finalizer routine for linux only

---

go.mod
test/framework/framework.go
test/framework/resource/aws/autoscaling/manager.go
test/framework/resource/k8s/node/manager.go
test/framework/resource/k8s/node/wrapper.go
test/integration/cninode/cninode_suite_test.go
test/integration/cninode/cninode_test.go
test/integration/perpodsg/perpodsg_suite_test.go
test/integration/perpodsg/perpodsg_test.go
test/integration/windows/windows_suite_test.go
test/integration/windows/windows_test.go

NA
Adding CNINode integration tests. 
```
[AfterSuite] 
/local/home/ravsushm/go/src/github.com/aws/amazon-vpc-resource-controller-k8s/test/integration/cninode/cninode_suite_test.go:41
STEP: verify CNINode count @ 03/28/24 08:48:55.193
STEP: checking number of CNINodes match number of nodes in the cluster @ 03/28/24 08:48:55.193
STEP: checking CNINode list matches node list @ 03/28/24 08:48:55.193
[AfterSuite] PASSED [0.000 seconds]
------------------------------
Ran 6 of 6 Specs in 491.652 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
Ginkgo ran 1 suite in 8m14.282438665s
Test Suite Passed
```
SGP tests:
```
Ran 19 of 23 Specs in 913.416 seconds
SUCCESS! -- 19 Passed | 0 Failed | 0 Pending | 4 Skipped
PASS
Ginkgo …
```

add CNINode integration tests

---

.github/workflows/presubmit.yaml
pkg/k8s/pod/converter.go
pkg/provider/branch/trunk/trunk.go
pkg/utils/events.go

N/A
Add `gosec` static analysis check in github actions. 
By default, this scans for high & medium issues. Excluding low issues as they are not very useful to fix(only low issues reported from local scan were many unhandled errors), also excludes test and generated files. 
Note on G108,G114: The go profiler is not enabled listening on a port be default, it is wrapped by an optional flag `enable-profiling`. This complies with a security best practice:
* only expose to localhost at a port which is not used for http server
* the controller doesn't open any endpoint to internet as a server
* the controller runs in isolated EKS control plane instance and doesn't server any traffic to/from outside world
By submitting this pull request, I …

add github action to run gosec static analysis

---

pkg/aws/ec2/api/cleanup/eni_cleanup.go
pkg/aws/ec2/api/cleanup/eni_cleanup_test.go
pkg/aws/ec2/api/helper.go
pkg/aws/ec2/api/helper_test.go
test/framework/options.go
test/framework/resource/aws/ec2/manager.go
test/integration/ec2api/ec2api_suite_test.go
test/integration/ec2api/ec2api_test.go

N/A
Use DescribeNetworkInterfaces EC2 API call with deep filters in v1.5.0 release. 
As pagination leads to more EC2 API calls, this can cause EC2 API throttling on the customer account. We will evaluate using pagination in the upcoming releases with some optimizations. 
Add integration test case for validating EC2 permissions on the controller
* verify controller is unable to delete ENIs not provisioned by the controller or vpc-cni (missing eks:eni:owner and other required tags)
* verify controller is able to create network interface permission on ENIs tagged with eks:eni:owner=eks-vpc-resource-controller
* verify controller is unable to create network interface permission on ENIs not tagged with eks:eni:owner=eks-vpc-resource-controller …

use DescribeNetworkInterfaces with deep filters

---

.github/workflows/presubmit.yaml
main.go
pkg/resource/introspect.go

N/A
Remove global exclusion of G108, G114 from github action and add `nosec` annotation in code to suppress current known false positives. 
```
gosec -exclude-dir test -exclude-generated -severity medium ./...
Summary:
Gosec  : dev
Files  : 53
Lines  : 11404
Nosec  : 3
Issues : 0
```

remove global exclusion for G108,G114 and add nosec in code

---

pkg/provider/branch/provider.go

Switching to logging library meant it doesn't do string formatting. The info call expects a key value pair instead of string format. When provided with odd number of arguments, this cause logger to panic
```
level: dpanic
logger: branch eni provider
msg: odd number of arguments passed as key-value pairs for logging
```

Fix log which causes panic

---

controllers/custom/builder.go
main.go
mocks/amazon-vcp-resource-controller-k8s/pkg/k8s/pod/mock_podapiwrapper.go
pkg/k8s/pod/client_wrapper.go
pkg/provider/branch/provider.go
pkg/provider/branch/provider_test.go
pkg/resource/introspect.go
pkg/resource/introspect_test.go

N/A
1. Adding handler for pod datastore operations to the introspect API
```
curl http://localhost:22775/datastore/all
{
"PodDatastore": {
"PodList": [
"default/sgp-cronjob-28573380-9jmwf",
"default/sgp-cronjob-28573380-jp8qj",
"default/sgp-cronjob-28573380-crpdd",
"default/hello-world-sgp-767766588-5fx78",
"default/sgp-cronjob-28573200-4zdkm",
"default/sgp-cronjob-28573200-h6wrj",
"kube-system/kube-proxy-hgtjm",
...
sh-4.2$ curl http://localhost:22775/datastore/node/ip-xxx
{
"ip-xxx": {
"Pods": {
"PodList": [
"default/sgp-cronjob-28573980-w2v5h",
"default/sgp-cronjob-28574040-z7hdf",
"default/sgp-cronjob-28573920-zzrp8",
"default/sgp-cronjob-28574040-mw8kg",
"default/sgp-cronjob-28574040-r27fs",
"default/sgp-cronjob-28574040-wdx54", …
```

add pod datastore to introspect, add logs for pod events

---

scripts/test/run-canary-test.sh
scripts/test/run-integration-tests.sh
test/integration/cninode/cninode_test.go

N/A
Run CNINode integration tests as part of the canary and full integration tests. 
```
Running Suite: CNINode Test Suite - /repository/vpc-resource-controller/build
Will run 6 of 6 specs
PASSED [0.000 seconds]
Ran 6 of 6 Specs in 490.177 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
Ginkgo ran 1 suite in 8m10.198094891s
Test Suite Passed
```

Add CNINode integration tests in canary

---

test/integration/cninode/cninode_test.go

N/A
This ensures there is always a node running in the cluster while running the cni nodes integration suite

Fix CNINodes integration test for internal testbed 

---

controllers/core/pod_controller.go
pkg/config/loader.go

- The burst is incorrectly set and qps is capped to smaller number. 
- We should use the same rate limiting for related API calls.
- Update the kubernetes client qps and burst to be same as controller-runtime default values.
- Double the pod reconciler workers.

QPS and busrt adjustment

---

README.md

Update readme to call out the controller version events will last for only one hour.

readme update for events

---

main.go

https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/442
```
The cloudwatch EKS cluster logs for vpc-resource-controller actions shows the userAgent field as:
"userAgent": "controller/v0.0.0 (linux/amd64) kubernetes/$Format",
```
The controller user agent is set in the kubeConfig / [client-go](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L491-L505) in this controller's case.
And it can be customized by updating `.UserAgent` of the kubeconfig used in making the call.
1. Built the VPC RC Image with this change.
2. Deployed it to Beta Clusters
3. Verified it Audit Logs
```
fields @timestamp, @message, @logStream
| filter @logStream like /audit/
| filter requestURI like /cninodes/
```
After this change the …

Set controller user-agent to vpc-resource-controller/git-version

---

controllers/core/configmap_controller.go
controllers/core/configmap_controller_test.go
docs/windows/secondary_ip_mode_config_options.md
pkg/config/loader.go
pkg/config/loader_test.go
pkg/config/type.go
pkg/pool/pool.go
pkg/pool/pool_test.go
pkg/pool/utils.go
pkg/pool/utils_test.go
pkg/provider/branch/provider.go
pkg/provider/ip/provider.go
pkg/provider/ip/provider_test.go
pkg/provider/prefix/provider.go
pkg/provider/prefix/provider_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go
scripts/test/run-integration-tests.sh
test/README.md
test/integration/windows/windows_test.go

> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
Resolves https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/428
This change introduces changes to provide configurable options for managing IP address allocation on Windows nodes when using secondary IP mode. The VPC Resource Controller will now allow configuring of the `windows-minimum-ip-target` and `windows-warm-ip-target` parameters in the `amazon-vpc-cni` ConfigMap. These parameters will control the minimum number of IP addresses to be allocated on each Windows node, and the number of 'warm' IP addresses to be pre-allocated respectively. The VPC RC will always ensure that based on the configurations, there will always be enough …

Add Windows secondary IP mode configurable options for managing IP address allocation

---

scripts/test/create-cluster-karpenter.sh
scripts/test/delete-cluster-karpenter.sh
test/README.md
test/framework/resource/aws/ec2/manager.go
test/framework/utils/resource.go
test/integration/scale/pod_scale_test.go
test/integration/scale/scale_suite_test.go

Adding scale tests for pods using security groups in Ginkgo, also added support to create EKS cluster with Karpenter installed. 
The ginkgo test suite creates a deployment with 1000 pods using security groups and the test is repeated three times. The EKS cluster is created with two nodes, and Karpenter should provision the required compute resources(EC2) to provision the pods. The expectation in each test is to have all pods in the deployment be ready within 5 mins. 
Test:
```
ginkgo -v --timeout 30m -- --cluster-kubeconfig=$KUBE_CONFIG_PATH --cluster-name=$CLUSTER_NAME --aws-region=$AWS_REGION --aws-vpc-id=$VPC_ID
Attempt #1 Passed.  Repeating ↺ @ 08/26/24 18:37:52.145
Attempt #2 Passed.  Repeating ↺ @ 08/26/24 18:45:27.071
Ran 1 of 1 Specs in 1579.915 seconds …
```

Add security group pods scale test in ginkgo

---

controllers/custom/builder.go
controllers/custom/custom_controller.go

solves #412 
As described in issue #412, controller data store gets partially hydrated if it received error 410. This is because reflector calls customized listFunc with page limit set to 0 but code was overwriting page limit, resulting in partial list instead of full list. This PR passes page limit option to cache config struct and let reflector handle state of options.limit as it will change it to 0 if it faces resource expired error.

Passing page limit to cach config instead of override.

---

go.mod
go.sum
pkg/aws/ec2/api/wrapper.go
pkg/aws/ec2/api/wrapper_test.go
pkg/utils/helper.go
pkg/utils/helper_test.go

N/A
This updates the aws-sdk-go and the way to get regional sts endpoint

Update aws-sdk-go and change way to get regional sts endpoint

---

pkg/aws/ec2/api/wrapper.go

N/A
We don't use global STS endpoint so in case global endpoint is not found, ignore and move ahead with regional STS provider 

Remove hard failure for not getting global STS endpoint

---

DEVELOPER_GUIDE.md
Makefile
config/controller/controller.yaml
pkg/provider/branch/provider.go
scripts/test/lib/config.sh

Updated the metrics to measure branch ENI operations- create branch ENI, annotate pod, and initialize trunk. The summary metric also measures 0.5, 0.9, 0.99 quantiles (50th, 90th, and 99th percentiles), and quantile 0(min value) & 1(max value). 
*Test*
Running scale tests to deploy 1K pods repeatedly:
```
branch_provider_operation_latency{branch_provider_operation="annotate_branch_eni",resource_count="1",quantile="0"} 9
branch_provider_operation_latency{branch_provider_operation="annotate_branch_eni",resource_count="1",quantile="0.5"} 15
branch_provider_operation_latency{branch_provider_operation="annotate_branch_eni",resource_count="1",quantile="0.9"} 35
branch_provider_operation_latency{branch_provider_operation="annotate_branch_eni",resource_count="1",quantile= …
```

update branch ENI operation metrics & dev guide

---

pkg/provider/branch/provider.go

Measure the latency in seconds to simplify dashboard and alarming. 

measure branch ENI operation latency in seconds

---

main.go

This MR is a part of effort to elevate single eks cluster performance by migrating the EKS components to use protobuf instead of json.
Modify kubeconfig type to use content type application/vnd.kubernetes.protobuf instead of json for performance gain.

use protobuf content type instead of json for k8s client

---

main.go

This reverts commit dd3564c30c5da8233d3ab5737ce331ee2fe0d10d.
Seeing errors, will fix these in a separate PR.

Revert "use protobuf content type instead of json for k8s client (#468)"

---

test/framework/utils/poll.go
test/integration/scale/pod_scale_test.go

For scale test 5 minutes is too tight of a deadline as node boot up takes varied amount of time. This is one my sample run where test failed because it took 0.0002 seconds more.
```
[FAILED] Expected
<float64>: 5.0002400429166665
to be <
<float64>: 5
In [It] at: /home/yathakka/go/src/github.com/aws/amazon-vpc-resource-controller-k8s/test/integration/scale/pod_scale_test.go:84 @ 10/18/24 20:39:57.763
```
Same for resource creation timeout. 

increasing timeout for few integration test

---

controllers/core/node_controller.go
mocks/amazon-vcp-resource-controller-k8s/pkg/node/manager/mock_manager.go
pkg/node/manager/manager.go
pkg/node/manager/manager_test.go
pkg/utils/errors.go

The controller shouldn't health check on resources when the upstream API returns some specific errors, such as EC2 throttling, since those errors are not recoverable by failing the controller.

Skipping health check on nodes if EC2 returns throttling errors

---

controllers/core/configmap_controller.go
controllers/core/node_controller.go
controllers/core/pod_controller.go
main.go
pkg/aws/ec2/api/wrapper.go
pkg/config/loader.go

#451 partly
1. Add support to configure controller parameters via flags, flags added 
```
nodeWorkerCount: The number of node workers, default 10
userClientQPS: The EC2 user client QPS rate, default 12
userClientBurst: The EC2 user client burst limit, default 18
instanceClientQPS: The EC2 instance client QPS rate, default 12
instanceClientBurst: The instance client burst limit, default 18
apiServerQPS: The API server client QPS rate, default 20
apiServerBurst: The API server client burst limit, default 30
maxPodConcurrentReconciles: The maximum number of concurrent reconciles for pod controller, default 20
maxNodeConcurrentReconciles: The maximum number of concurrent reconciles for node controller, default 10
```
Customers can configure …

Add flags to configure controller parameters

---

test/integration/cninode/cninode_test.go

The test that are skipped fails when control plane does not have updated manifest of cni-node and changes from vpc-cni which add cluster tag key.

skipping test until manifest update

---

controllers/crds/cninode_controller.go
controllers/crds/cninode_controller_test.go
pkg/aws/ec2/api/cleanup/eni_cleanup.go
pkg/aws/ec2/api/cleanup/eni_cleanup_test.go
pkg/aws/ec2/api/helper.go
pkg/aws/ec2/api/helper_test.go
pkg/aws/ec2/api/wrapper.go
pkg/config/type.go
pkg/k8s/wrapper.go
test/integration/cninode/cninode_test.go

We will keep two describe ENI calls for each cleanup, along with common filters we will add this filter for each call 
-  `"kubernetes.io/cluster/$Cluster_name":owned` 
-  `"cluster.k8s.amazonaws.com/name":$Cluster_name` 
Both are different cluster tags used by VPC-RC and VPC-CNI for the ENI it creates
Testing Procedure:
1. deployed master branch  vpc-cni on cluster
2. Passed Cluster name to vpc-cni env variable
3. Deployed workload
4. Detached one of the ENI created by vpc-cni. 
5. Confirmed from the logs of vpc-rc that it cleaned up that eni created by vpc-cni
Also did the same test with trunk interface of node.  to check if VPC-RC cluster name are pushed 
By submitting this pull request, I confirm that you can use, modify, copy, and …

keeping cluster tag filter of vpc-cni and vpc-rc

---

controllers/crds/cninode_controller.go
controllers/crds/cninode_controller_test.go
main.go
pkg/aws/ec2/api/cleanup/node_cleanup.go
pkg/config/type.go
pkg/provider/branch/trunk/trunk.go
pkg/provider/branch/trunk/trunk_test.go

skipping node cleaner if node-id tag not present in cninode is not present.
Test:
For node-id not present
1. made sure node-id not present in cninode.
2. detached the eni
3. deleted the node.
4. verified eni's were not deleted by node cleaner.
Also did same test with node-id and observed eni's were cleaned

skipping node cleaner if node id is not present

---

Dockerfile
Makefile

N/A
This makes sure we build with the latest go-runner everytime

Updatign go runner version

---

apis/vpcresources/v1beta1/securitygrouppolicy_types.go
config/crd/bases/vpcresources.k8s.aws_cninodes.yaml
config/crd/bases/vpcresources.k8s.aws_securitygrouppolicies.yaml
config/rbac/role.yaml
hack/toolchain.sh

Removing the validation in security groups where we limit IDs by 5.
Regenerated CRD spec with newest controller-gen version. 
We will open fail now if Cx quota for security group per network interface is less than what it matches to pod. 
Created SGP with 7 group ids, quota in my account was 5.
We failed to create pod 
```
failed to allocate branch ENI to pod: creating network interface, operation error EC2: CreateNetworkInterface, https response error StatusCode: 400, RequestID: f3c2ff75-4ed5-433e-a797-c15a27804f8d, api error InvalidParameterValue: user 975050023620 exceeded limit 5 on the number of interface security group memberships
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

removing security group limit of 5 from crd
