aws/amazon-vpc-resource-controller-k8s

- README.md
Updated readme with go report
*Issue #, if available:* N/A
Update readme with go report card
> Updated readme with go report

- test/framework/resource/k8s/sgp/wrapper.go
The following test case is quite flaky and consistently fails. It's failing when trying to get a SGP just after it's created as cache is not yet populated with the new SGP.
```
Branch ENI Pods creating branch pods when adding new security group to a existing SGP 
a new pod should run with all security groups
/repository/vpc-resource-controller/test/integration/perpodsg/perpodsg_test.go:280
STEP: creating the namespace if not exist
STEP: creating the security group policy
STEP: updating the security group policy
STEP: deleting the pod
STEP: deleting security group policy
STEP: deleting the namespace
• Failure [6.351 seconds]
Branch ENI Pods
/repository/vpc-resource-controller/test/integration/perpodsg/perpodsg_test.go:33
creating branch pods …
```
> fix flaky integration test for pod sgp

- Dockerfile
- Makefile
- config/controller/controller.yaml
- config/default/kustomization.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- controllers/core/pod_controller.go
Sync manifest generated using Kustomize. 
> sync manifest generated using kustomize

- test/integration/run.sh
Provide ability to pass EKS endpoint on describing cluster in test script.
> pass endpoint when describing eks test cluster

- Dockerfile
- pkg/aws/ec2/api/wrapper.go
N/A
Use go-runner for log redirection. 
> Use go-runner for logging

- main.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/pool/mock_pool.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/provider/branch/trunk/mock_trunk.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/provider/mock_provider.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/resource/mock_resources.go
- pkg/node/node_test.go
- pkg/pool/pool.go
- pkg/pool/pool_test.go
- pkg/provider/branch/provider.go
- pkg/provider/branch/provider_test.go
- pkg/provider/branch/trunk/trunk.go
- pkg/provider/branch/trunk/trunk_test.go
- pkg/provider/ip/provider.go
- pkg/provider/ip/provider_test.go
- pkg/provider/provider.go
- pkg/resource/introspect.go
- pkg/resource/introspect_test.go
- pkg/resource/manager.go
- pkg/resource/manager_test.go
*Issue #, if available:* #34 
Add introspect API for debugging issues with all Resources across all managed Nodes. This API can later be exposed for customers if required.
Example output.
**Introspect a Node**
```
curl 192.168.6.143:22775/node/ip-192-168-28-99.us-west-2.compute.internal
{
"vpc.amazonaws.com/PrivateIPv4Address": {
"UsedResources": {
"019e0387-df0a-4ec1-a449-76e73a3219c6": "192.168.10.187/19",
"5a1008ce-7d5e-45fa-8d8c-16b8c9b69b24": "192.168.26.221/19"
},
"WarmResources": [
"192.168.23.206/19",
"192.168.9.91/19",
"192.168.30.13/19"
],
"CoolingResources": null
},
"vpc.amazonaws.com/pod-eni": {}
```
```
curl 192.168.6.143:22775/node/ip-192-168-74-131.us-west-2.compute.internal
{
"vpc.amazonaws.com/PrivateIPv4Address": {},
"vpc.amazonaws.com/pod-eni": …
```
> Add Introspect API for debugging resources across all managed nodes

- config/rbac/role.yaml
- controllers/core/configmap_controller.go
- controllers/core/configmap_controller_test.go
- controllers/core/suite_test.go
- main.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/k8s/mock_k8swrapper.go
- pkg/condition/conditions.go
- pkg/config/type.go
- pkg/k8s/wrapper.go
- pkg/k8s/wrapper_test.go
- pkg/node/manager/manager.go
- pkg/node/manager/manager_test.go
- scripts/test/test-with-eksctl.sh
- test/framework/framework.go
- test/framework/manifest/configmap.go
- test/framework/manifest/pod.go
- test/framework/resource/k8s/configmap/manager.go
- test/framework/resource/k8s/configmap/wrapper.go
- test/framework/resource/k8s/node/manager.go
- test/framework/resource/k8s/node/wrapper.go
- test/framework/utils/poll.go
- test/framework/verify/pod.go
- test/integration/windows/stress_test.go
- test/integration/windows/windows_suite_test.go
- test/integration/windows/windows_test.go
1. Added controller to watch for ConfigMap changes
2. Handle Windows IPAM updates on ConfigMap changes
3. Added test cases
> ConfigMap to enable/disable Windows IPAM

- scripts/test/run-canary-test.sh
*Issue #, if available:* Fixes flaky Canary Tests.
Fixes the follow flaky failure 
- Check vpc-cni DS rollout status before running Ginko tests.
- Install stable version of aws-node.
> Install stable version of vpc-cni addon

- scripts/test/run-canary-test.sh
Canary Script was failing for 1.17 cluster because add-ons are supported from 1.18 onward.
> Install vpc-cni via manifest for EKS 1.17 Clusters in Canary script

- README.md
Update README for EKS Windows Support.
> update README for v1.1.0 Release

- webhooks/core/annotation_validation_webhook.go
Switching from Service Account to User based authentication.
> allow controller user to annotate pod with networking info

- Makefile
- scripts/test/run-canary-test.sh
Run Test via Ginkgo Build as it's easier to ship as dockerfile.
> run ginkgo test via binary

- scripts/test/run-canary-test.sh
*Issue #, if available:* Canary tests are stuck in infitinite loop, if vpc-cni add on doesn't become ready. With this change we do limited retries.
> do limited retries when checking addon status

- Makefile
- scripts/test/lib/cluster.sh
- scripts/test/run-canary-test.sh
Merge test-prow branch to master.
Tests are stable now and we can run tests directly against master branch.
> merge test-prow to master

- test/integration/webhook/validating_webhook_test.go
Fix the integration test against node webhook
> Fix the integration test

- pkg/aws/vpc/README.md
#129 
We want to add a README to limit.go file in release branch since there is a divergence between released limit file and latest limit file in master branch.  
> add README for limit file

- pkg/k8s/wrapper.go
- pkg/k8s/wrapper_test.go
#144 
If node is returned with nil capacity map for any reason, the controller will panic due to missing mechanism to handle `panic: assignment to entry in nil map`. We need to handle this case gracefully and make it retriable. By explicitly returning a `Conflict` error, the RetryOnConflict will retry till default back timeout
```
var DefaultBackoff = wait.Backoff{
Steps:    4,
Duration: 10 * time.Millisecond,
Factor:   5.0,
Jitter:   0.1,
}
``` 
Tests
e2e for security group for pods
```
[AfterSuite] PASSED [90.838 seconds]
[AfterSuite] 
/home/zhuhz/go/src/amazon-vpc-resource-controller-k8s/test/integration/perpodsg/perpodsg_suite_test.go:58
Begin Captured GinkgoWriter Output >>
STEP: waiting for all the ENIs to be deleted after being …
```
> handle nil capacity map gracefully and make it retriable

- config/certmanager/certificate.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
> update deprecated apis

- main.go
We have been through the migration process for a while. Now it is time to change from ConfigMapLease to Lease only. Changes include
1. a new flag to enable Lease only in terms of supporting model in EKS cluster versions
2. if the flag is true, the controller will start with LeaseResourceLock instead of ConfigMapLeaseResourceLock
Tests
1. enabled lease-only
2. confirmed ConfigMap wasn't renewed but Lease was
3. deleted the ConfigMap, no impact the controller execution
4. deleted the Lease, the Lease was recreated and no impact to controller
5. disabled lease-only
6. ConfigMap was recreated and renewed with Lease
7. deleted ConfigMap and Lease, both of them were recreated and renewed
By submitting this pull request, I confirm that you can …
> change to use lease only

- controllers/core/node_controller.go
- controllers/core/node_controller_test.go
- main.go
Due to possible performance impact, we want to disable the event controller for now. Further assessment or alternative solution is work-in-progress.
> disable event controller

- config/crd/bases/vpcresources.k8s.aws_cninodes.yaml
- go.mod
- go.sum
#226 
We need to upgrade controller runtime to take the fix from https://github.com/kubernetes-sigs/controller-runtime/pull/2219
> upgrade controller runtime version

- pkg/provider/prefix/provider.go
- Added healthz check to prefix provider to implement the provider interface
> added healthz check to prefix provider

- controllers/core/pod_controller.go
- controllers/core/pod_controller_test.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/node/mock_node.go
- pkg/node/node.go
- pkg/node/node_test.go
- pkg/provider/prefix/provider.go
- pkg/provider/prefix/provider_test.go
- added nitro check to prefix provider
> added nitro check to prefix provider and pod controller

- pkg/provider/ip/provider.go
- pkg/provider/prefix/provider.go
- Changed node capacity initialization to only exclude the used IPs from the alternative provider. When a node joins, or the controller restarts, both IPv4 provider and prefix provider are initialized with respective calculated capacity. Previously this capacity calculation would exclude any used or warm IPs of the alternative provider. This change made the calculation only exclude the used IPs, not the warm IPs. That way when user toggles from one mode to the other, if there was no used secondary IP or prefix from the previous mode, the node capacity would be accurate for the new mode. 
> changed node capacity initialization to only exclude the used IPs from the alternative provider

- test/framework/resource/aws/ec2/manager.go
- test/framework/utils/poll.go
- test/framework/verify/pod.go
- test/integration/windows/windows_test.go
- Added integ test for `warm-ip-target`
- Added integ test for `minimum-ip-target`
- Refactored function to check if pod's IP is from a prefix
> added more integration tests for PD configs

- pkg/provider/ip/provider.go
- pkg/provider/prefix/provider.go
- Change node capacity initialization to full for each IP resource provider
- When PD is enabled, log if prefix IP provider observes capacity discrepancy due to running pods from secondary IP mode during initialization
- When PD is disabled, log if secondary IP provider observes capacity discrepancy due to running pods from PD mode during initialization
> initialize node capacity to full and send node event for discrepancy

- pkg/node/manager/manager_test.go
- test/framework/framework.go
- test/framework/resource/k8s/node/manager.go
- test/integration/perpodsg/perpodsg_test.go
We should add new test cases to new CNINode operation.
> Update unit tests and integration tests for CNINode

- config/rbac/role.yaml
- main.go
We want to minimize the scope of the CNINode permissions. Delete and Patch won't be needed by this controller
> Rbac scope down on CNINode

- README.md
The controller provides its version during runtime when a node is created. This PR updates the README to instruct how to check the information.
> update README to provide instructions to check its version

- go.mod
- go.sum
We need update golang package protobuf to 1.33.0.
> update protobuf to 1.33.0

- scripts/test/run-integration-tests.sh
N/A
Increase windows timeout to 120m
> Increase windows test timeout

- controllers/core/node_controller.go
- controllers/core/node_controller_test.go
- mocks/amazon-vcp-resource-controller-k8s/pkg/aws/ec2/mock_instance.go
- pkg/aws/ec2/instance.go
- pkg/node/manager/manager.go
- pkg/provider/branch/trunk/trunk.go
- pkg/provider/branch/trunk/trunk_test.go
> Adding cninode leak metrics and cninode finalizer handler.

- DEVELOPER_GUIDE.md
- Makefile
- config/controller/controller.yaml
- pkg/provider/branch/provider.go
- scripts/test/lib/config.sh
Cherry picking PR #465, #469 to update branch ENI operation latency metrics for release 1.6
Testing details in PR #465
> Cherry pick- branch ENI operation metrics 

- main.go
Merge master commits into feature branch & rebase
> use protobuf content type instead of json for k8s client (#484)

- controllers/core/node_controller_test.go
> adding test to assert that we requeue on internal server error

- Dockerfile
> updating go runner image tag for cve fix

- pkg/node/manager/manager.go
> adding log level to noisy log

- controllers/crds/cninode_controller.go
- controllers/crds/cninode_controller_test.go
- main.go
- pkg/aws/ec2/api/cleanup/eni_cleanup.go
- pkg/aws/ec2/api/cleanup/eni_cleanup_test.go
- pkg/aws/ec2/api/cleanup/node_cleanup.go
- pkg/aws/ec2/api/helper.go
- pkg/aws/ec2/api/helper_test.go
- pkg/aws/ec2/api/wrapper.go
- pkg/config/type.go
- pkg/k8s/wrapper.go
- pkg/node/manager/manager.go
- pkg/provider/branch/trunk/trunk.go
- pkg/provider/branch/trunk/trunk_test.go
- test/integration/cninode/cninode_test.go
> Release 1.7.2

- Dockerfile
- go.mod
- go.sum
> dep upgrade for cve

- Dockerfile
- go.mod
- go.sum
> updrading dependency for cve fix

- controllers/custom/custom_controller.go
- main.go
- Reduce controller cache sync polling interval from 5s to 1s for faster startup
- Increase default page size to 1000 for faster iteration of objects
> Improve controller performance and startup time

- Dockerfile
> bumping up go runner tag
